### PR TITLE
akx20000 0.15.0.2 gitian OSX signed sigs

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by h4x3rotab** [comment]
Looks like you forgot to resolve conflicts.

**Comment by akx20000a** [comment]
@h4x3rotab Forgot to rebase before commiting but I did resolved conflicts now hehe

**Comment by ghost** [comment]
@h4x3rotab Looks like it has been gone awkward hmmm

**Comment by ghost** [comment]
Reopening request

**Pull request closed without merging**
